// Fixed demo trip used by `npm run db:seed` and by the planner tests.
// Hard-coded on purpose: the seed must be deterministic.

export type SeedReaction = "IN" | "MAYBE" | "SKIP";

export type SeedWish = {
  author: number; // index into SEED_MEMBERS
  title: string;
  notes?: string;
  kind: "ACTIVITY" | "CONSTRAINT";
  priority: "MUST" | "LOVE" | "NICE";
  timeOfDay: "EARLY_MORNING" | "MORNING" | "AFTERNOON" | "EVENING" | "NIGHT" | "ANY";
  durationHrs: number;
  costLevel: number;
  energy: number;
  tags: string[];
  in?: number[];
  maybe?: number[];
  skip?: number[];
};

export const SEED_TRIP = {
  id: "demo-trip",
  code: "DEMO42",
  name: "Bali with the crew",
  destination: "Bali, Indonesia",
  startDate: new Date("2026-11-02T00:00:00.000Z"),
  endDate: new Date("2026-11-06T00:00:00.000Z"), // 5 days
  createdAt: new Date("2026-10-01T09:00:00.000Z"),
};

// The first member is the host. Tokens are fixed so you can sign in as anyone
// locally by setting the cookie `tm_DEMO42=<token>`. The seed never runs in
// production.
export const SEED_MEMBERS = [
  "Alex",
  "Priya",
  "Sam",
  "Jordan",
  "Mei",
  "Tomás",
  "Aisha",
  "Ben",
  "Kai",
  "Noor",
].map((name, i) => ({
  id: `demo-member-${i}`,
  name,
  isHost: i === 0,
  token: `demo-token-${i}`,
}));

const [ALEX, PRIYA, SAM, JORDAN, MEI, TOMAS, AISHA, BEN, KAI, NOOR] = SEED_MEMBERS.map((_, i) => i);

export const SEED_WISHES: SeedWish[] = [
  {
    author: ALEX,
    title: "Sunrise hike up Mount Batur",
    kind: "ACTIVITY",
    priority: "MUST",
    timeOfDay: "EARLY_MORNING",
    durationHrs: 4,
    costLevel: 0,
    energy: 3,
    tags: ["hike", "views"],
    in: [PRIYA, JORDAN, TOMAS, AISHA, BEN],
    maybe: [NOOR],
    skip: [MEI],
  },
  {
    author: ALEX,
    title: "Street food night market",
    kind: "ACTIVITY",
    priority: "LOVE",
    timeOfDay: "EVENING",
    durationHrs: 2,
    costLevel: 1,
    energy: 1,
    tags: ["food"],
    in: [SAM, JORDAN, MEI, TOMAS, AISHA, NOOR, BEN],
  },
  {
    author: PRIYA,
    title: "Balinese cooking class",
    kind: "ACTIVITY",
    priority: "MUST",
    timeOfDay: "AFTERNOON",
    durationHrs: 3,
    costLevel: 2,
    energy: 1,
    tags: ["food", "culture"],
    in: [MEI, AISHA, NOOR, ALEX, JORDAN],
    maybe: [SAM],
  },
  {
    author: PRIYA,
    title: "Spa afternoon",
    kind: "ACTIVITY",
    priority: "NICE",
    timeOfDay: "AFTERNOON",
    durationHrs: 3,
    costLevel: 3,
    energy: 0,
    tags: ["relax"],
    in: [MEI],
    skip: [SAM],
  },
  {
    author: SAM,
    title: "Free walking tour of Ubud",
    kind: "ACTIVITY",
    priority: "MUST",
    timeOfDay: "MORNING",
    durationHrs: 3,
    costLevel: 0,
    energy: 1,
    tags: ["culture"],
    in: [ALEX, PRIYA, JORDAN, MEI, AISHA, BEN, NOOR],
  },
  {
    author: SAM,
    title: "Beach day at Padang Padang",
    kind: "ACTIVITY",
    priority: "LOVE",
    timeOfDay: "ANY",
    durationHrs: 6,
    costLevel: 0,
    energy: 0,
    tags: ["beach", "relax"],
    in: [ALEX, PRIYA, MEI, TOMAS, AISHA, BEN, KAI],
  },
  {
    author: JORDAN,
    title: "Scuba diving at the Liberty wreck",
    kind: "ACTIVITY",
    priority: "MUST",
    timeOfDay: "MORNING",
    durationHrs: 6,
    costLevel: 3,
    energy: 3,
    tags: ["water", "adventure"],
    in: [TOMAS, BEN],
    maybe: [ALEX],
    skip: [MEI, SAM],
  },
  {
    author: JORDAN,
    title: "Rooftop bar in Seminyak",
    kind: "ACTIVITY",
    priority: "NICE",
    timeOfDay: "NIGHT",
    durationHrs: 2,
    costLevel: 2,
    energy: 1,
    tags: ["nightlife"],
    in: [TOMAS, BEN, KAI, ALEX],
  },
  {
    author: MEI,
    title: "Botanical garden picnic",
    kind: "ACTIVITY",
    priority: "LOVE",
    timeOfDay: "MORNING",
    durationHrs: 3,
    costLevel: 0,
    energy: 0,
    tags: ["relax", "nature"],
    in: [PRIYA, NOOR, SAM],
    maybe: [ALEX, AISHA],
  },
  {
    author: MEI,
    title: "Traditional tea ceremony",
    kind: "ACTIVITY",
    priority: "MUST",
    timeOfDay: "AFTERNOON",
    durationHrs: 2,
    costLevel: 1,
    energy: 0,
    tags: ["culture"],
    in: [PRIYA, NOOR, AISHA, SAM, ALEX],
  },
  {
    author: TOMAS,
    title: "Surf lesson in Canggu",
    kind: "ACTIVITY",
    priority: "LOVE",
    timeOfDay: "MORNING",
    durationHrs: 3,
    costLevel: 2,
    energy: 3,
    tags: ["water", "adventure"],
    in: [JORDAN, BEN, KAI],
  },
  {
    author: TOMAS,
    title: "Live music bar crawl",
    kind: "ACTIVITY",
    priority: "MUST",
    timeOfDay: "NIGHT",
    durationHrs: 3,
    costLevel: 1,
    energy: 2,
    tags: ["nightlife", "music"],
    in: [JORDAN, BEN, KAI, ALEX, AISHA, SAM],
    skip: [MEI],
  },
  {
    author: AISHA,
    title: "Museum Puri Lukisan",
    kind: "ACTIVITY",
    priority: "MUST",
    timeOfDay: "MORNING",
    durationHrs: 3,
    costLevel: 1,
    energy: 1,
    tags: ["culture", "art"],
    in: [PRIYA, MEI, NOOR],
    maybe: [SAM, ALEX],
  },
  {
    author: AISHA,
    title: "Sunset boat cruise",
    kind: "ACTIVITY",
    priority: "LOVE",
    timeOfDay: "EVENING",
    durationHrs: 3,
    costLevel: 2,
    energy: 0,
    tags: ["water", "views"],
    in: [ALEX, PRIYA, JORDAN, MEI, TOMAS, BEN, KAI, NOOR],
    skip: [SAM],
  },
  {
    author: BEN,
    title: "Mountain bike the rice terraces",
    kind: "ACTIVITY",
    priority: "LOVE",
    timeOfDay: "AFTERNOON",
    durationHrs: 4,
    costLevel: 2,
    energy: 3,
    tags: ["adventure", "nature"],
    in: [JORDAN, TOMAS],
  },
  {
    author: BEN,
    title: "Craft brewery tour",
    kind: "ACTIVITY",
    priority: "MUST",
    timeOfDay: "AFTERNOON",
    durationHrs: 2,
    costLevel: 2,
    energy: 1,
    tags: ["food", "nightlife"],
    in: [TOMAS, KAI, JORDAN, ALEX],
  },
  {
    // Kai's only MUST, and nobody else wants it: exercises the fairness pass.
    author: KAI,
    title: "Retro arcade museum",
    kind: "ACTIVITY",
    priority: "MUST",
    timeOfDay: "ANY",
    durationHrs: 2,
    costLevel: 1,
    energy: 1,
    tags: ["games"],
    skip: [ALEX, PRIYA, SAM, MEI, AISHA, NOOR],
  },
  {
    author: KAI,
    title: "Karaoke night",
    kind: "ACTIVITY",
    priority: "LOVE",
    timeOfDay: "NIGHT",
    durationHrs: 2,
    costLevel: 1,
    energy: 2,
    tags: ["nightlife", "music"],
    in: [ALEX, JORDAN, TOMAS, AISHA, BEN, PRIYA],
  },
  {
    author: NOOR,
    title: "Vegetarian warung crawl",
    kind: "ACTIVITY",
    priority: "MUST",
    timeOfDay: "AFTERNOON",
    durationHrs: 3,
    costLevel: 1,
    energy: 1,
    tags: ["food"],
    in: [PRIYA, MEI, AISHA],
  },
  {
    author: NOOR,
    title: "Yoga on the beach",
    kind: "ACTIVITY",
    priority: "NICE",
    timeOfDay: "EARLY_MORNING",
    durationHrs: 1,
    costLevel: 0,
    energy: 1,
    tags: ["relax", "beach"],
    in: [MEI],
    maybe: [PRIYA],
  },
  {
    author: ALEX,
    title: "Kayak the mangroves",
    kind: "ACTIVITY",
    priority: "NICE",
    timeOfDay: "MORNING",
    durationHrs: 3,
    costLevel: 2,
    energy: 2,
    tags: ["water", "nature"],
    in: [JORDAN, TOMAS, BEN],
  },
  {
    author: SAM,
    title: "Thrift and flea market",
    kind: "ACTIVITY",
    priority: "NICE",
    timeOfDay: "MORNING",
    durationHrs: 2,
    costLevel: 0,
    energy: 0,
    tags: ["shopping"],
    maybe: [MEI],
  },
  {
    author: JORDAN,
    title: "Waterfall day trip",
    kind: "ACTIVITY",
    priority: "LOVE",
    timeOfDay: "ANY",
    durationHrs: 8,
    costLevel: 2,
    energy: 2,
    tags: ["nature", "views"],
    in: [ALEX, TOMAS, AISHA, BEN, KAI, PRIYA],
    maybe: [NOOR],
  },
  {
    author: MEI,
    title: "Bookshop café crawl",
    kind: "ACTIVITY",
    priority: "NICE",
    timeOfDay: "AFTERNOON",
    durationHrs: 2,
    costLevel: 1,
    energy: 0,
    tags: ["relax"],
    in: [PRIYA],
  },
  {
    author: BEN,
    title: "Night photography walk",
    kind: "ACTIVITY",
    priority: "NICE",
    timeOfDay: "NIGHT",
    durationHrs: 2,
    costLevel: 0,
    energy: 1,
    tags: ["art"],
  },
  {
    author: PRIYA,
    title: "Pottery workshop",
    kind: "ACTIVITY",
    priority: "LOVE",
    timeOfDay: "MORNING",
    durationHrs: 2,
    costLevel: 2,
    energy: 0,
    tags: ["art", "culture"],
    in: [MEI, AISHA, NOOR],
  },
  // Constraints: never scheduled, only used for conflict detection.
  {
    author: PRIYA,
    title: "No early mornings please",
    notes: "I'm useless before 9.",
    kind: "CONSTRAINT",
    priority: "NICE",
    timeOfDay: "ANY",
    durationHrs: 0.5,
    costLevel: 0,
    energy: 0,
    tags: [],
  },
  {
    author: SAM,
    title: "Budget under $50/day",
    kind: "CONSTRAINT",
    priority: "NICE",
    timeOfDay: "ANY",
    durationHrs: 0.5,
    costLevel: 0,
    energy: 0,
    tags: [],
  },
  {
    author: MEI,
    title: "Keep it chill, lots of rest",
    kind: "CONSTRAINT",
    priority: "NICE",
    timeOfDay: "ANY",
    durationHrs: 0.5,
    costLevel: 0,
    energy: 0,
    tags: [],
  },
  {
    author: NOOR,
    title: "Vegetarian food only",
    kind: "CONSTRAINT",
    priority: "NICE",
    timeOfDay: "ANY",
    durationHrs: 0.5,
    costLevel: 0,
    energy: 0,
    tags: [],
  },
];

/** Stable ids and createdAt (one minute apart) so planner tie-breaks are reproducible. */
export const seedWishId = (i: number) => `demo-wish-${String(i).padStart(2, "0")}`;
export const seedWishCreatedAt = (i: number) =>
  new Date(SEED_TRIP.createdAt.getTime() + (i + 1) * 60_000);
